<?= 
foreach ($skills as $skill): ?>
  
    <?=$skill['name']?> <?=$skill['value']?>
    
    <?php endforeach;?>
    
$skills=[
    [
        'name'=>'PHP',
        'level'=>'90'
    ],
    [
        'name'=>'HTML',
        'level'=>'80'
    ],
    [
        'name'=>'CSS',
        'level'=>'80'
    ],
    [
        'name'=>'JS',
        'level'=>'70'
    ],
    [
        'name'=>'SQL',
        'level'=>'70'
    ],
    [
        'name'=>'Laravel',
        'level'=>'70'
    ],
    [
        'name'=>'Vue',
        'level'=>'60'
    ],
    [
        'name'=>'React',
        'level'=>'60'
    ],
    [
        'name'=>'Node',
        'level'=>'60'
    ],
    [
        'name'=>'Python',
        'level'=>'50'
    ],
    [
        'name'=>'Django',
        'level'=>'50'
    ],
    [
        'name'=>'C#',
        'level'=>'50'
    ],
    [
        'name'=>'C++',
        'level'=>'50'
    ],
    [
        'name'=>'Java',
        'level'=>'50'
    ],
    [
        'name'=>'C',
        'level'=>'50'
    ],
    [
        'name'=>'Photoshop',
        'level'=>'50'
    ],
    [
        'name'=>'Illustrator',
        'level'=>'50'
    ],
    [
        'name'=>'After Effects',
        'level'=>'50'
    ],
    [
        'name'=>'Premiere',
        'level'=>'50'
    ],
    [
        'name'=>'Blender',
        'level'=>'50'
    ],
    [
        'name'=>'Unity',
        'level'=>'50'
    ],
    [
        'name'=>'Unreal',
        'level'=>'50'
    ],
    [
        'name'=>'Git',
        'level'=>'50'
    ],
    [
        'name'=>'Linux',
        'level'=>'50'
    ],
    [
        'name'=>'Windows',
        'level'=>'50'
    ],
    [
        'name'=>'Mac',
        'level'=>'50'
    ],
    [
        'name'=>'Android',
        'level'=>'50'
    ],
    [
        'name'=>'IOS',
        'level'=>'50'
    ],
    [
        'name'=>'SEO',
        'level'=>'50'
    ],
    [
        'name'=>'Google Analytics',
        'level'=>'50'
    ],
    [
        'name'=>'Google Ads',
    ]
]
?>